---
fixtures:
  repositories:
    stdlib:
      ref: "v6.6.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    sshkeys_core:
      ref: "2.2.0"
      repo: "https://github.com/puppetlabs/puppetlabs-sshkeys_core"
    mount_core:
      ref: "1.0.4"
      repo: "https://github.com/puppetlabs/puppetlabs-mount_core"
    apt:
      ref: "v7.7.1"
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
    docker:
      ref: "v3.13.1"
      repo: "https://github.com/puppetlabs/puppetlabs-docker"
    unattended_upgrades:
      ref: "v5.1.0"
      repo: "https://github.com/voxpupuli/puppet-unattended_upgrades"
    ntp:
      ref: "v8.3.0"
      repo: "https://github.com/puppetlabs/puppetlabs-ntp"
  symlinks:
    vision_base: '#{source_dir}'
